---
- name: Install taps
  homebrew_tap:
    name: '{{ item }}'
  with_items: '{{ homebrew_taps }}'

- name: Update Homebrew and install Homebrew packages
  homebrew:
    name: '{{ item }}'
    update_homebrew: yes
  with_items: '{{ homebrew_packages }}'

- name: Install Homebrew cask applications
  homebrew_cask:
    name: '{{ item }}'
  with_items: '{{ homebrew_cask_apps }}'

- name: Install composer global packages
  composer:
    command: require
    global_command: yes
    arguments: '{{ item }}'
  with_items: '{{ composer_packages }}'

- name: Install Mac App Store applications
  command: 'mas install {{ item }}'
  with_items: '{{ mas_apps }}'
