---
- name: Install taps
  homebrew_tap:
    name: '{{ item }}'
  with_items: '{{ homebrew_taps }}'

- name: Update Homebrew and upgrade all packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install Homebrew packages
  homebrew:
    name: '{{ item }}'
  with_items: '{{ homebrew_packages }}'

- name: Cleanup Homebrew packages
  command: brew cleanup

- name: Install Homebrew cask applications
  homebrew_cask:
    name: '{{ item }}'
    install_options: force
  with_items: '{{ homebrew_cask_apps }}'

- name: Cleanup Homebrew cask applications
  command: brew cask cleanup

- name: Install Atom packages
  command: 'apm install {{ item }}'
  with_items: '{{ atom_packages }}'

- name: Install Vagrant plugins
  command: 'vagrant plugin install {{ item }}'
  with_items: '{{ vagrant_plugins }}'

- name: Install composer global packages
  composer:
    command: require
    global_command: yes
    arguments: '{{ item }}'
  with_items: '{{ composer_packages }}'

- name: Install Mac App Store applications
  command: 'mas install {{ item }}'
  with_items: '{{ mas_apps }}'
