---
- name: Download theme
  get_url:
    url: https://raw.githubusercontent.com/sindresorhus/iterm2-snazzy/master/Snazzy.itermcolors
    dest: /tmp

- name: Remove theme
  file:
    path: /tmp/Snazzy.itermcolors
    state: absent
